stages:
  - first
  - second
  - third

print_first:
  stage: first
  tags:
    - dev
  only:
    - develop
  script:
    - echo "Hello world first"

print_second:
  stage: second
  tags:
    - dev
  only:
    - develop
  script:
    - echo "Hello world second"

print_third:
  stage: third
  tags:
    - dev
  only:
    - develop
  script:
    - echo "Hello world third"
