version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - app
    container_name: ${CONTAINER_PREFIX}_nginx

  app:
    image: $REGISTRY/dev/app:$CI_COMMIT_SHA
    environment:
      - APP_NAME=$APP_NAME
      - APP_ENV=$APP_ENV
      - APP_KEY=$APP_KEY
      - APP_DEBUG=$APP_DEBUG
      - APP_URL=$APP_URL
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: ${CONTAINER_PREFIX}_app

  db:
    image: postgres:14
    restart: always
    volumes:
        - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
        - 5432:5432
    container_name: ${CONTAINER_PREFIX}_db
